# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=woot_revived
mod_name=Woot Revived
mod_version=1.0.7-beta

# Platform Properties
java_version=21
mc_version=1.21.1
neo_version=21.1.172

# Dependency Properties
jei_version=19.21.1.304
jade_version=15.10.0+neoforge
guideme_version=21.1.9
kubejs_version=2101.7.0-build.131

# KubeJS Dependencies
rhino_version=2100.2.5-build.48

# Optimization Mods
embeddium_version=1.0.16-beta.3+mc1.21.1
modernfix_version=5.24.3+mc1.21.1-neoforge
ferritecore_version=7.0.2-neoforge