modLoader = "javafml"
loaderVersion = "[${neo_major_version},)"
issueTrackerURL = "https://github.com/pharuxtan/woot"
license = "LGPLv3"

[[mods]]
modId = "woot_revived"
version = "${file.jarVersion}"
displayName = "Woot Revived"
authors = "pharuxtan"
credits = "Ipsis"
description = '''A big, bad, magic, multiblock for mob drops. Aparrently you will either love it or hate it. There is no inbetween.'''

[[dependencies.woot_revived]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_version}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.woot_revived]]
modId = "forge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"
